SELECT 
/*+ USE_NL(EMP DEPT) */
EMP.EMPNO, EMP.ENAME, DEPT.DNAME
FROM EMP
JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO;

SELECT
/*+ FULL(EMP) */
    EMPNO, SAL, DEPTNO
FROM EMP
WHERE SAL >= 3000 AND DEPTNO = 10;

select
/*+  PARALLEL(EBA_DEMO_IG_PEOPLE, 4) */
    NAME, COUNTRY, RATING 
from EBA_DEMO_IG_PEOPLE;