SELECT * FROM LAPTOPS
ORDER BY ID
FETCH FIRST 15 ROWS ONLY;

SELECT min(DISPLAY_SIZE), min(SSD), min(HDD), min(RAM) from LAPTOPS;

SELECT MAX(DISPLAY_SIZE) - MIN(DISPLAY_SIZE) RANGE_DISPLAY_SIZE,
        MAX(SSD) - MIN(SSD) RANGE_SSD,
        MAX(HDD) - MIN(HDD) RANGE_HDD,
        MAX(RAM) - MIN(RAM) RANGE_RAM
FROM LAPTOPS;

SELECT  BRAND, LAPTOP_NAME,
(DISPLAY_SIZE - MIN(DISPLAY_SIZE) OVER ())/ (MAX(DISPLAY_SIZE) OVER () - MIN(DISPLAY_SIZE) OVER ()) NORM_DISPLAY_SIZE,
(SSD - MIN(SSD) OVER ())/ (MAX(SSD) OVER () - MIN(SSD) OVER ()) NORM_SSD,
(HDD - MIN(HDD) OVER ())/ (MAX(HDD) OVER () - MIN(HDD) OVER ()) NORM_HDD,
ROUND((RAM - MIN(RAM) OVER ())/ (MAX(RAM) OVER () - MIN(RAM) OVER ()), 3) NORM_RAM
FROM LAPTOPS
ORDER BY ID
FETCH FIRST 15 ROWS ONLY;

SELECT BRAND, LAPTOP_NAME, PROCESSOR_TYPE,
ROUND(5 * (HDD - MIN(HDD) OVER ())/ (MAX(HDD) OVER ()- MIN(HDD) OVER ()) +
(SSD - MIN(SSD) OVER ())/ (MAX(SSD) OVER () - MIN(SSD) OVER ()) +
2 * (DISPLAY_SIZE - MIN(DISPLAY_SIZE) OVER ())/ (MAX(DISPLAY_SIZE) OVER () - MIN(DISPLAY_SIZE) OVER ()) +
2 * (RAM - MIN(RAM) OVER ())/ (MAX(RAM) OVER () -  MIN(RAM) OVER ()) , 3) AS F
FROM LAPTOPS ORDER BY 4 DESC
FETCH FIRST 15 ROWS ONLY;